# Generated by Django 4.2 on 2023-04-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoptaki", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="description",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="garage",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="title",
        ),
        migrations.AddField(
            model_name="listing",
            name="days_listed",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="listing",
            name="img",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.DecimalField(decimal_places=9, default=-1, max_digits=12),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.DecimalField(decimal_places=9, default=-1, max_digits=12),
        ),
        migrations.AddField(
            model_name="listing",
            name="rent_estimate",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="listing",
            name="address",
            field=models.CharField(default="5000 Forbes Ave", max_length=200),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bedrooms",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(default="Pittsburgh", max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="lot_size",
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="listing",
            name="sqft",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="listing",
            name="state",
            field=models.CharField(default="PA", max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="zipcode",
            field=models.CharField(default=-1, max_length=20),
        ),
    ]
