# Generated by Django 4.2 on 2023-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptaki', '0002_remove_listing_description_remove_listing_garage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=5, default=-1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_estimate',
            field=models.DecimalField(decimal_places=5, default=-1, max_digits=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=20),
        ),
    ]
