# Generated by Django 4.2 on 2023-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptaki', '0003_alter_listing_bathrooms_alter_listing_lot_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_rate', models.IntegerField()),
                ('loan_to_value', models.IntegerField()),
                ('current_savings', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('amort_sched', models.IntegerField()),
            ],
        ),
    ]
