# Generated by Django 4.2 on 2023-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptaki', '0004_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('monthly_noi', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('p_interest', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('p_fcf', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('p_cashoncash', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('p_debtyield', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('p_debtconstant', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('pandi_principal', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('pandi_fcf', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('pandi_cashoncash', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('pandi_debtyield', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('pandi_debtconstant', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
            ],
        ),
    ]
