# Generated by Django 4.2 on 2023-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptaki', '0005_listinganalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinganalytics',
            name='pandi_interest',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=20),
        ),
    ]
